

export const data = {
  // 请求方式
  "axios-type": [
    { label: "get", value: "1" },
    { label: "post", value: "2" },
    { label: "put", value: "3" },
    { label: "delete", value: "4" },
    { label: "head", value: "5" },
    { label: "options", value: "6" },
    { label: "patch", value: "7" },
  ],
  "menu-type": [
    { label: "菜单", value: "1" },
    { label: "目录", value: "2" },
  ],
};
// 受理局数据代码
export const countryData = [
  {
    label: '知识产权五局',
    children: [
      { label: '美国', value: 'US' },
      { label: '中国', value: 'CN' },
      { label: '欧洲专利局', value: 'EP' },
      { label: '日本', value: 'JP' },
      { label: '韩国', value: 'KR' }
    ]
  },
  {
    label: '主要受理局',
    children: [
      { label: '世界知识产权组织', value: 'WO' },
      { label: '奥地利', value: 'AT' },
      { label: '澳大利亚', value: 'AU' },
      { label: '比利时', value: 'BE' },
      { label: '比荷卢经济联盟', value: 'BX' },
      { label: '加拿大', value: 'CA' },
      { label: '瑞士', value: 'CH' },
      { label: '德国', value: 'DE' },
      { label: '丹麦', value: 'DK' },
      { label: '西班牙', value: 'ES' },
      { label: '欧盟', value: 'EU' },
      { label: '芬兰', value: 'FI' },
      { label: '法国', value: 'FR' },
      { label: '英国', value: 'UK' },
      { label: '中国香港', value: 'HK' },
      { label: '爱尔兰', value: 'IE' },
      { label: '以色列', value: 'IL' },
      { label: '印度', value: 'IN' },
      { label: '中国澳门', value: 'MO' },
      { label: '荷兰', value: 'NL' },
      { label: '挪威', value: 'NO' },
      { label: '新西兰', value: 'NZ' },
      { label: '波兰', value: 'PL' },
      { label: '俄罗斯', value: 'RU' },
      { label: '瑞典', value: 'SE' },
      { label: '新加坡', value: 'SG' },
      { label: '泰国', value: 'TH' },
      { label: '中国台湾', value: 'TW' }
    ]
  },
  {
    label: '其他受理局',
    children: [
      { label: '埃塞俄比亚', value: 'ET' },
      { label: '阿曼', value: 'OM' },
      { label: '巴拿马', value: 'PA' },
      { label: '秘鲁', value: 'PE' },
      { label: '斐济', value: 'FJ' },
      { label: '巴布亚新几内亚', value: 'PG' },
      { label: '菲律宾', value: 'PH' },
      { label: '海湾地区阿拉伯国家合作委员会专利局', value: 'GC' },
      { label: '巴基斯坦', value: 'PK' },
      { label: '格鲁吉亚', value: 'GE' },
      { label: '加纳', value: 'GH' },
      { label: '巴勒斯坦', value: 'PS' },
      { label: '希腊', value: 'GR' },
      { label: '葡萄牙', value: 'PT' },
      { label: '安道尔', value: 'AD' },
      { label: '危地马拉', value: 'GT' },
      { label: '巴拉圭', value: 'PY' },
      { label: '阿拉伯联合酋长国', value: 'AE' },
      { label: '圭亚那', value: 'GY' },
      { label: '卡塔尔', value: 'QA' },
      { label: '安提瓜和巴布达', value: 'AG' },
      { label: '罗马尼亚', value: 'RO' },
      { label: '安圭拉', value: 'AI' },
      { label: '洪都拉斯', value: 'HN' },
      { label: '塞尔维亚共和国', value: 'RS' },
      { label: '阿尔巴尼亚', value: 'AL' },
      { label: '克罗地亚', value: 'HR' },
      { label: '亚美尼亚', value: 'AM' },
      { label: '匈牙利', value: 'HU' },
      { label: '卢旺达', value: 'RW' },
      { label: '安哥拉', value: 'AO' },
      { label: '印度尼西亚', value: 'ID' },
      { label: '沙特阿拉伯', value: 'SA' },
      { label: '非洲地区工业产权组织', value: 'AP' },
      { label: '所罗门群岛', value: 'SB' },
      { label: '阿根廷', value: 'AR' },
      { label: '塞舌尔', value: 'SC' },
      { label: '苏丹', value: 'SD' },
      { label: '阿鲁巴', value: 'AW' },
      { label: '伊拉克', value: 'IQ' },
      { label: '阿塞拜疆', value: 'AZ' },
      { label: '伊朗', value: 'IR' },
      { label: '波斯尼亚和黑塞哥维那', value: 'BA' },
      { label: '冰岛', value: 'IS' },
      { label: '斯洛文尼亚', value: 'SI' },
      { label: '巴巴多斯', value: 'BB' },
      { label: '意大利', value: 'IT' },
      { label: '斯洛伐克', value: 'SK' },
      { label: '孟加拉国', value: 'BD' },
      { label: '泽西', value: 'JE' },
      { label: '圣马力诺', value: 'SM' },
      { label: '约旦', value: 'JO' },
      { label: '圣多美和普林西比', value: 'ST' },
      { label: '保加利亚', value: 'BG' },
      { label: '肯尼亚', value: 'KE' },
      { label: '前苏联', value: 'SU' },
      { label: '巴林', value: 'BH' },
      { label: '吉尔吉斯斯坦', value: 'KG' },
      { label: '萨尔瓦多', value: 'SV' },
      { label: '百慕大', value: 'BM' },
      { label: '柬埔寨', value: 'KH' },
      { label: '叙利亚', value: 'SY' },
      { label: '文莱', value: 'BN' },
      { label: '开曼群岛', value: 'KY' },
      { label: '特克斯和凯科斯群岛', value: 'TC' },
      { label: '玻利维亚', value: 'BO' },
      { label: '哈萨克斯坦', value: 'KZ' },
      { label: '巴西', value: 'BR' },
      { label: '老挝', value: 'LA' },
      { label: '塔吉克斯坦', value: 'TJ' },
      { label: '巴哈马', value: 'BS' },
      { label: '黎巴嫩', value: 'LB' },
      { label: '土库曼斯坦', value: 'TM' },
      { label: '不丹', value: 'BT' },
      { label: '列支敦士登', value: 'LI' },
      { label: '突尼斯', value: 'TN' },
      { label: '博茨瓦纳', value: 'BW' },
      { label: '斯里兰卡', value: 'LK' },
      { label: '汤加', value: 'TO' },
      { label: '立陶宛', value: 'LT' },
      { label: '土耳其', value: 'TR' },
      { label: '白俄罗斯', value: 'BY' },
      { label: '卢森堡', value: 'LU' },
      { label: '特立尼达和多巴哥', value: 'TT' },
      { label: '伯利兹', value: 'BZ' },
      { label: '拉脱维亚', value: 'LV' },
      { label: '摩洛哥', value: 'MA' },
      { label: '坦桑尼亚', value: 'TZ' },
      { label: '刚果(金)', value: 'CD' },
      { label: '摩纳哥', value: 'MC' },
      { label: '乌克兰', value: 'UA' },
      { label: '刚果(布)', value: 'CG' },
      { label: '摩尔多瓦', value: 'MD' },
      { label: '乌干达', value: 'UG' },
      { label: '黑山共和国', value: 'ME' },
      { label: '乌拉圭', value: 'UY' },
      { label: '智利', value: 'CL' },
      { label: '马达加斯加', value: 'MG' },
      { label: '乌兹别克斯坦', value: 'UZ' },
      { label: '哥伦比亚', value: 'CO' },
      { label: '北马其顿共和国', value: 'MK' },
      { label: '圣文森特和格林纳丁斯', value: 'VC' },
      { label: '哥斯达黎加', value: 'CR' },
      { label: '缅甸', value: 'MM' },
      { label: '委内瑞拉', value: 'VE' },
      { label: '捷克和斯洛伐克共和国', value: 'CS' },
      { label: '蒙古', value: 'MN' },
      { label: '英属维尔京群岛', value: 'VG' },
      { label: '古巴', value: 'CU' },
      { label: '越南', value: 'VN' },
      { label: '佛得角', value: 'CV' },
      { label: '蒙特塞拉特', value: 'MS' },
      { label: '萨摩亚', value: 'WS' },
      { label: '塞浦路斯', value: 'CY' },
      { label: '马耳他', value: 'MT' },
      { label: '科索沃', value: 'XK' },
      { label: '捷克', value: 'CZ' },
      { label: '毛里求斯', value: 'MU' },
      { label: '也门', value: 'YE' },
      { label: '东德', value: 'DD' },
      { label: '马拉维', value: 'MW' },
      { label: '南斯拉夫', value: 'YU' },
      { label: '吉布提', value: 'DJ' },
      { label: '墨西哥', value: 'MX' },
      { label: '南非', value: 'ZA' },
      { label: '马来西亚', value: 'MY' },
      { label: '赞比亚', value: 'ZM' },
      { label: '多米尼克', value: 'DM' },
      { label: '莫桑比克', value: 'MZ' },
      { label: '桑给巴尔', value: 'ZN' },
      { label: '多米尼加共和国', value: 'DO' },
      { label: '纳米比亚', value: 'NA' },
      { label: '津巴布韦', value: 'ZW' },
      { label: '阿尔及利亚', value: 'DZ' },
      { label: '尼日利亚', value: 'NG' },
      { label: '欧亚专利局', value: 'EA' },
      { label: '尼加拉瓜', value: 'NI' },
      { label: '厄瓜多尔', value: 'EC' },
      { label: '爱沙尼亚', value: 'EE' },
      { label: '埃及', value: 'EG' },
      { label: '非洲知识产权组织', value: 'OA' }
    ]
  }
];

// 法律状态数据代码
export const legalStatusData = [
  { label: '失效', value: 0 },
  { label: '有效', value: 1 },
  { label: '审中', value: 2 },
  { label: 'PCT指定期满', value: 220 },
  { label: 'PCT指定期内', value: 221 },
  { label: '未确认', value: 999 }
]